# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-ttrss-cnlpete

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Tiny Tiny RSS Reader
Version:    0.7.3
Release:    1
Group:      Applications/Internet
License:    GPLv2+
URL:        http://ttrss.cnlpete.de/
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-ttrss-cnlpete.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   qt5-plugin-imageformat-ico
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(sailfishapp) >= 0.0.10
BuildRequires:  qt5-qttools-linguist
BuildRequires:  desktop-file-utils

%description
ttrss is a Tiny Tiny RSS Reader App for the Nokia N9 and the Jolla
smartphone, written using Qt/QML. It uses the Tiny Tiny RSS JSON
API.

%if "%{?vendor}" == "chum"
PackageName: TTRSS
Type: desktop-application
Categories:
  - Network
  - News
Custom:
  Repo: https://github.com/cnlpete/ttrss
Icon: https://raw.githubusercontent.com/cnlpete/ttrss/master/images/icons/256x256/harbour-ttrss-cnlpete.png
Screenshots:
 - https://github.com/cnlpete/ttrss/raw/ttrss.cnlpete.de/assets/screenshots/sailfish/feeditem.jpg
 - https://github.com/cnlpete/ttrss/raw/ttrss.cnlpete.de/assets/screenshots/sailfish/feeds.jpg
 - https://github.com/cnlpete/ttrss/raw/ttrss.cnlpete.de/assets/screenshots/sailfish/categories.jpg
Url:
  Donation: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=WUWGSGAK8K7ZN
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5  \
    VERSION=%{version} \
    RELEASE=%{release} \
    harbour-ttrss-cnlpete.pro

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
%{_datadir}/icons/hicolor/108x108/apps/%{name}.png
%{_datadir}/icons/hicolor/128x128/apps/%{name}.png
%{_datadir}/icons/hicolor/172x172/apps/%{name}.png
%{_datadir}/icons/hicolor/256x256/apps/%{name}.png
# >> files
# << files
