name: build all arch for sailfish

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build App
    strategy:
      matrix:
        arch: ['armv7hl', 'aarch64', 'i486']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Prepare
      run: mkdir output

    - name: Build (${{ matrix.arch }})
      uses: coderus/github-sfos-build@master
      with:
        arch: ${{ matrix.arch }}
        release: 4.5.0.16

    - name: Upload RPM (${{ matrix.arch }})
      uses: actions/upload-artifact@v4
      with:
        name: rpm-${{ matrix.arch }}
        path: RPMS

  release:
    runs-on: ubuntu-latest
    name: Release App
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download RPM
      uses: actions/download-artifact@v4
      with:
        path: RPMS
        merge-multiple: true

    - name: Display structure of downloaded files
      run: ls -R ./

    - name: Extract Version Name
      id: extract_name
      uses: actions/github-script@v4
      with:
        result-encoding: string
        script: |
          return context.payload.ref.replace(/refs\/tags\//, '');

    - name: Create a Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ steps.extract_name.outputs.result }}
        draft: false
        prerelease: false
        body: This release was autogenerated.
        files: 'RPMS/*.rpm'


